___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [18]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [19]:
my_list=[5,10,15,20,25]
np.array(my_list)


array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [21]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 5. Make all the values of the array above 7

#### 6. Create same array above with full method

In [22]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [23]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [24]:
np.arange(0,25).reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [25]:
np.linspace(((0,25,1)),dtype=int)

TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'

#### 10. Create 5 random number with numpy

In [ ]:
np.random.random(5)

array([0.23096315, 0.46314923, 0.9929258 , 0.00582936, 0.58562409])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.random((5,5))

array([[0.30815123, 0.36638452, 0.01243037, 0.82299534, 0.45676328],
       [0.45224842, 0.18858301, 0.79782771, 0.14583149, 0.74345267],
       [0.62214789, 0.00737094, 0.48287583, 0.95133556, 0.06877475],
       [0.86224665, 0.20351188, 0.44209896, 0.82953026, 0.22338365],
       [0.82216353, 0.12075363, 0.92141409, 0.04155249, 0.81941166]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,50,(3,4))

array([[34, 29, 23, 44],
       [27, 24, 30, 37],
       [40, 37, 36, 28]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
ranarr = np.random.randint(0, 60, (6,8))
ranarr

array([[31, 29, 37, 38, 23, 57, 19, 32],
       [25,  5, 50, 34,  5, 53, 13, 40],
       [10,  8,  5, 49, 24, 22, 26,  0],
       [ 6, 26, 43, 47, 38,  0, 52, 57],
       [14,  5, 20, 14, 59, 18, 46, 37],
       [40, 23, 44, 14, 37, 21, 15,  2]])

array([[31, 17, 58,  3, 11, 19, 12, 35],
       [28, 18, 52, 24, 41, 40, 14, 56],
       [48,  8, 15,  7, 45,  3,  1, 56],
       [40, 53, 13, 29, 33,  2, 45, 46],
       [53, 19, 33, 21, 37, 52, 41, 25],
       [54, 52,  3,  7, 36, 30, 37, 42]])

In [ ]:
#reshape with -1
ranarr.reshape(-1,8)

array([[31, 29, 37, 38, 23, 57, 19, 32],
       [25,  5, 50, 34,  5, 53, 13, 40],
       [10,  8,  5, 49, 24, 22, 26,  0],
       [ 6, 26, 43, 47, 38,  0, 52, 57],
       [14,  5, 20, 14, 59, 18, 46, 37],
       [40, 23, 44, 14, 37, 21, 15,  2]])

## Numpy Indexing and Selection


In [ ]:
#Create array below
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [ ]:
a = np.array([[6,7],[10,11]])
a


array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [ ]:
a[:,1:2]

array([[ 7],
       [11]])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
a[1,:]

array([10, 11])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
a= np.arange(1,17).reshape(4,4)
a
a[:,2:3]=77
a
a[:,3:]=77
a

array([[ 1,  2, 77, 77],
       [ 5,  6, 77, 77],
       [ 9, 10, 77, 77],
       [13, 14, 77, 77]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [ ]:
a[1:,2:3]


array([[77],
       [77],
       [77]])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
a[]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
a= np.arange(1,17).reshape(4,4)
a
a[:,2:3]=77
a

c =a[a<10]
c


array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
b = a[a>12]
b

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
b+c

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
a= np.arange(1,17).reshape(4,4)
a
a[:,2:3]=77
#a[:,3:]=77
a
np.std(a)

30.004166377354995

#### 22. Get the sum of second column from array above

In [ ]:
#print array here  
a= np.arange(1,17).reshape(4,4)
a
a[:,2:3]=77
a
a[:,3:]=77
a

array([[ 1,  2, 77, 77],
       [ 5,  6, 77, 77],
       [ 9, 10, 77, 77],
       [13, 14, 77, 77]])

In [ ]:
np.sum(a[:,1:2])

32

#### 23. Get the median,mean and std of 3rd column from array above

In [ ]:
#median
a= np.arange(1,17).reshape(4,4)
a
a[:,2:3]=77
a
np.median(a)

11.0

In [ ]:
#mean
np.mean(a)

25.5

In [ ]:
#std
np.std(a)

30.004166377354995

# Pandas Section

In [27]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [28]:
df = pd.read_csv("C:/Users/LENOVO/Desktop/ME/1.CLRSWY/1.DATA SCIENCE/PANDAS/Salaries.csv").head(5)
df

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Id                5 non-null      int64  
 1   EmployeeName      5 non-null      object 
 2   JobTitle          5 non-null      object 
 3   BasePay           5 non-null      float64
 4   OvertimePay       5 non-null      float64
 5   OtherPay          5 non-null      float64
 6   Benefits          0 non-null      float64
 7   TotalPay          5 non-null      float64
 8   TotalPayBenefits  5 non-null      float64
 9   Year              5 non-null      int64  
 10  Notes             0 non-null      float64
 11  Agency            5 non-null      object 
 12  Status            0 non-null      float64
dtypes: float64(8), int64(2), object(3)
memory usage: 648.0+ bytes


In [30]:
df.describe()

Id        BasePay    OvertimePay       OtherPay  Benefits  \
count  5.000000       5.000000       5.000000       5.000000       0.0   
mean   3.000000  149686.786000   83415.554000  186997.944000       NaN   
std    1.581139   49279.467429   99747.068306  138838.049118       NaN   
min    1.000000   77916.000000       0.000000   16452.600000       NaN   
25%    2.000000  134401.600000    9737.000000  137811.380000       NaN   
50%    3.000000  155966.020000   56120.710000  182234.590000       NaN   
75%    4.000000  167411.180000  106088.180000  198306.900000       NaN   
max    5.000000  212739.130000  245131.880000  400184.250000       NaN   

            TotalPay  TotalPayBenefits    Year  Notes  Status  
count       5.000000          5.000000     5.0    0.0     0.0  
mean   420100.284000     420100.284000  2011.0    NaN     NaN  
std    122015.258729     122015.258729     0.0    NaN     NaN  
min    326373.190000     326373.190000  2011.0    NaN     NaN  
25%    332343.610000     332343.610000  2011.0    NaN     NaN  
50%    335279.910000     335279.910000  2011.0    NaN     NaN  
75%    538909.280000     538909.280000  2011.0    NaN     NaN  
max    567595.430000     567595.430000  2011.0    NaN     NaN

**How many different year value are there**

In [31]:
df = pd.read_csv("C:/Users/LENOVO/Desktop/ME/1.CLRSWY/1.DATA SCIENCE/PANDAS/Salaries.csv")
df
df['Year'].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [32]:
#max
df['TotalPay'].max()

567595.43

In [34]:
#avg
df['TotalPay'].mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [35]:
df = pd.read_csv("C:/Users/LENOVO/Desktop/ME/1.CLRSWY/1.DATA SCIENCE/PANDAS/Salaries.csv")
df
#df.count(df['TotalPay']> df['TotalPay'].mean())
#df.count(level='TotalPay')
#df['TotalPay'].value_counts(sort=True, ascending=True)
df['TotalPay'].value_counts(df['TotalPay']>df['TotalPay'].mean())

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**How much does ALBERT PARDINI make (including benefits)?**

In [36]:
# yanlış 
['TotalPayBenefits'].value_counts()

AttributeError: 'list' object has no attribute 'value_counts'

**Who is lowest paid person**

In [53]:
# lowest_paid = df.min()
# lowest_paid
#df['TotalPay'].idxmin()
df[df['TotalPay'] == df['TotalPay'].min()]    # formata göre eksik


Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653   -618.13       0.0   -618.13           -618.13  2014    NaN   

               Agency  Status  
148653  San Francisco     NaN

**What are the unique Jobs in dataset?**

In [54]:
df.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [55]:
df.nsmallest(3, 'JobTitle')

TypeError: Column 'JobTitle' has dtype object, cannot use method 'nsmallest' with this dtype

**How many people earned more than avg in 2012**

20366

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...        
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object