___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [78]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [79]:
my_list=[5,10,15,20,25]
np.array(my_list)


array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [80]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [81]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [82]:
np.ones((4,4), dtype=int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [83]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [84]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [85]:
np.arange(0,25).reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [86]:
np.linspace(0,24,25, dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [87]:
np.random.random(5)

array([0.41446372, 0.06336867, 0.75864977, 0.27438362, 0.99263568])

#### 11. Create random normal distributed 5x5 array

In [88]:
np.random.random(size=(5,5))

array([[0.61780113, 0.36896593, 0.55181554, 0.32705508, 0.21429887],
       [0.06843026, 0.78685101, 0.43631285, 0.67970062, 0.73102579],
       [0.66794256, 0.08993193, 0.38917319, 0.88037926, 0.8994969 ],
       [0.24372427, 0.97965484, 0.6966188 , 0.24708932, 0.97254394],
       [0.27790913, 0.36589761, 0.46696753, 0.18985962, 0.11547794]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [89]:
np.random.randint(20,50,size=(3,4))

array([[37, 31, 39, 20],
       [44, 26, 23, 39],
       [48, 23, 30, 32]])

#### 13. Reshape the array below with shape 6x8

In [90]:
ranarr = np.random.randint(0, 60, 48)
ranarr

array([30, 16, 19,  8, 58, 19, 13, 18, 33,  5, 25, 26, 21, 29, 37, 15, 17,
       58,  2, 17, 16, 21, 34,  2, 11, 11, 18, 45, 41, 18,  5, 32,  3,  5,
       40, 20,  9, 54, 20, 55, 56,  0, 57, 54, 41, 11, 10, 26])

In [91]:
ranarr.reshape(6,8)

array([[30, 16, 19,  8, 58, 19, 13, 18],
       [33,  5, 25, 26, 21, 29, 37, 15],
       [17, 58,  2, 17, 16, 21, 34,  2],
       [11, 11, 18, 45, 41, 18,  5, 32],
       [ 3,  5, 40, 20,  9, 54, 20, 55],
       [56,  0, 57, 54, 41, 11, 10, 26]])

In [92]:
#reshape with -1
ranarr.reshape(-1,8)

array([[30, 16, 19,  8, 58, 19, 13, 18],
       [33,  5, 25, 26, 21, 29, 37, 15],
       [17, 58,  2, 17, 16, 21, 34,  2],
       [11, 11, 18, 45, 41, 18,  5, 32],
       [ 3,  5, 40, 20,  9, 54, 20, 55],
       [56,  0, 57, 54, 41, 11, 10, 26]])

## Numpy Indexing and Selection


In [93]:
#Create array below
arr =np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [94]:
arr= np.array([[6,7],[10,11]])
arr


array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [95]:
arr[:,0]

array([ 6, 10])

#### 16. Get the values in 2nd row for every 2 step.

In [96]:
arr[1,0::2]

array([10])

#### 17.Assign 77 to every cell in 3rd column.

In [97]:
arr= np.arange(1,17).reshape(4,4)
arr
arr[:,2:3]=77
arr


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [98]:
arr[[1,3],[0,2]]


array([ 5, 77])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [99]:
arr[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [100]:
arr[a<10]



NameError: name 'a' is not defined

In [ ]:
arr[a>12]

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
b = arr[a<10] + arr[a>12]
b

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
b.std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here  
arr

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
np.sum(a[:,1:2])

32

#### 23. Get the median,mean and std of 3rd column from array above

In [ ]:
#median
c= np.arange(1,17).reshape(4,4)
c


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.median(c[2,:])

10.5

In [ ]:
#mean
c[2,:].mean()

10.5

In [ ]:
#std
c[2,:].std()

1.118033988749895

# Pandas Section

In [101]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [102]:
df = pd.read_csv("C:/Users/LENOVO/Desktop/ME/1.CLRSWY/1.DATA SCIENCE/PANDAS/Salaries.csv")

In [103]:
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [105]:
df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year value are there**

In [106]:
df = pd.read_csv("C:/Users/LENOVO/Desktop/ME/1.CLRSWY/1.DATA SCIENCE/PANDAS/Salaries.csv")
df
df['Year'].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [ ]:
#max
df['TotalPay'].max()

567595.43

In [ ]:
#avg
df['TotalPay'].mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [ ]:
df = pd.read_csv("C:/Users/LENOVO/Desktop/ME/1.CLRSWY/1.DATA SCIENCE/PANDAS/Salaries.csv")
df
len(df[df['TotalPay'] > df['TotalPay'].mean()])

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [ ]:
df['TotalPayBenefits'][df['EmployeeName'] == 'ALBERT PARDINI']

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [ ]:
df['TotalPay'].min() 


-618.13

In [ ]:
df[df['TotalPay'] == -618.13]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [ ]:
df.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [ ]:
df['JobTitle'].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [ ]:
# olmadı
df['Id'][(df['TotalPayBenefits'] > df['TotalPayBenefits'].mean()) & (df['Year'] == 2012)].count()

20366

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here
x = df.apply(lambda x: x.str.contains('Manager', case=False) if x.name in ['JobTitle'] else x)['JobTitle']
x.sum()

4110

In [107]:
def jobtitle(job_title):
    if 'manager' in job_title.lower():
        return True
    else:
        return False
sum(df['JobTitle'].apply(lambda x: jobtitle(x)))


4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [ ]:
sal_new=df.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [ ]:
al_new = df.loc[:, ['EmployeeName', 'JobTitle', 'TotalPay', 'TotalPayBenefits']]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [ ]:
df['EmployeeName'][(df['TotalPayBenefits'] > df['TotalPayBenefits'].min()) | 
                   (df['TotalPayBenefits'] < df['TotalPayBenefits'].mean())]

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...        
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object

In [108]:
employeesmittel = df.where(((df["TotalPayBenefits"])<(df["TotalPayBenefits"].mean()))&((df["TotalPayBenefits"])>(df["TotalPayBenefits"].min())))
employeesmittel["EmployeeName"]


0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
              ...      
148649    Roy I Tillery
148650     Not provided
148651     Not provided
148652     Not provided
148653              NaN
Name: EmployeeName, Length: 148654, dtype: object